name: Job with matrix
on:
    push
jobs:
    node-js-app:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ["18","22","16"]
        steps:
            - name: setup node js version
              uses: actions/setup-node@v6
              with:
                node-version: ${{matrix.node-version}}

            - name: check node version
              run: node -v
            